-- Se crea el usuario para la db

-- CREATE USER dbJavaTest IDENTIFIED BY dbpass QUOTA UNLIMITED ON USERS DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;

-- GRANT create session TO dbJavaTest;
-- GRANT create table TO dbJavaTest;
-- GRANT create view TO dbJavaTest;
-- GRANT create any trigger TO dbJavaTest;
-- GRANT create any procedure TO dbJavaTest;
-- GRANT create sequence TO dbJavaTest;
-- GRANT create synonym TO dbJavaTest;
-- GRANT CONNECT, RESOURCE TO dbJavaTest;

drop table DBJAVATEST.GENDERS;
drop table DBJAVATEST.JOBS;
drop table DBJAVATEST.EMPLOYEES;
drop table DBJAVATEST.EMPLOYEE_WORKED_HOURS;

CREATE TABLE DBJAVATEST.GENDERS (
	ID NUMBER,
	NAME VARCHAR2(255) NOT NULL,
	CONSTRAINT GENDERS_PK PRIMARY KEY (ID)
);
CREATE TABLE DBJAVATEST.JOBS (
	ID NUMBER,
	NAME             VARCHAR2(255) NOT NULL ,
	SALARY               NUMBER(9,2) NOT NULL ,
	CONSTRAINT  JOBS_PK PRIMARY KEY (ID)
);
CREATE TABLE DBJAVATEST.EMPLOYEES (
	ID NUMBER,
	GENDER_ID NUMBER,
	JOB_ID NUMBER,
	NAME VARCHAR2(255) NOT NULL,
	LAST_NAME VARCHAR2(255),
	BIRTHDATE DATE,
	CONSTRAINT EMPLOYEES_PK PRIMARY KEY (ID),
	CONSTRAINT FK_GENDERS FOREIGN KEY (ID) REFERENCES DBJAVATEST.GENDERS(ID),
	CONSTRAINT FK_JOBS FOREIGN KEY (ID) REFERENCES DBJAVATEST.JOBS(ID)
);
CREATE TABLE DBJAVATEST.EMPLOYEE_WORKED_HOURS (
	ID NUMBER,
	EMPLOYEE_ID NUMBER,
	WORKED_HOURS NUMBER,
	WORKED_DATE DATE,
	CONSTRAINT EMPLOYEE_WORKED_HOURS_PK PRIMARY KEY (ID),
	CONSTRAINT FK_EMPLOYEES FOREIGN KEY (ID) REFERENCES DBJAVATEST.EMPLOYEES(ID)
);